#!/bin/sh

func=$1
shift

case "${func}" in
	show) # Print all checks
		eval "${CALL_FUNCTION}"
		;;
	all) # Verify all known environments
		eval "${CALL_FUNCTION}"
		;;
	list-functions)
		list_module_functions "${BASH_SOURCE[0]}"
		;;
	help|*) # Print this help
		show_help "${BASH_SOURCE[0]}"
		;;
esac
