version: 2

jobs:

  shellcheck:
    working_directory: /work
    docker: [{image: 'docker:17.06-git'}]
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
          exclusive: false
      - run:
          name: "Run shellcheck"
          command: |
            dockerfile=.ci/dockerfiles/Dockerfile.shellcheck
            echo "COPY . ." >> $dockerfile
            docker build -f $dockerfile --tag cli-validator:$CIRCLE_BUILD_NUM .
            docker run --rm \
                cli-validator:$CIRCLE_BUILD_NUM \
                make shellcheck
  test:
    working_directory: /work
    docker: [{image: 'docker:17.06-git'}]
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Run test zsh"
          command: |
            dockerfile=.ci/dockerfiles/Dockerfile.test.zsh
            echo "COPY . ." >> $dockerfile
            docker build -f $dockerfile --tag cli-builder:$CIRCLE_BUILD_NUM .
            docker run --rm \
                cli-builder:$CIRCLE_BUILD_NUM \
                make test-unit
      - run:
          name: "Run test bash"
          command: |
            mkdir -p /work/arftifacts/bash
            dockerfile=.ci/dockerfiles/Dockerfile.test.bash
            echo "COPY . ." >> $dockerfile
            docker build -f $dockerfile --tag cli-builder:$CIRCLE_BUILD_NUM .
            docker run --rm \
#                -v /work/artifacts/bash:/work \
                cli-builder:$CIRCLE_BUILD_NUM \
                make test-unit
      - store_artifacts:
          path: /work/artifacts

workflows:
  version: 2
  ci:
    jobs:
      - shellcheck
      - test
