#!/bin/sh

#DOE_HOME=~/.doe
source  ~/.doe/doe.presets

case ${1:-verify} in
	verify) # Verify all known environments
		source ${DOE_HOME}/doe.verify.sh ${2:-all}
		;;
	vagrant) # doe vagrant module commands
		source ${DOE_HOME}/doe.vagrant.sh ${2:-help}
		;;
	help|*) # Print this help
		echo "Usage:\n\tdoe\n\tdoe  <command>\n\nCommnads:"
		grep ") #[ ]" $BASH_SOURCE | sed "s/) #/$(echo "\t")/g"
		;;
esac
