#!/bin/sh

set -e

echo "$0: shellcheck bin/doe"
shellcheck bin/doe
echo "$0: shellcheck <(bin/doe completion)"
bin/doe list-modules
echo "$SHELL"
env
echo "$0: find .ci/scripts/ -type f -exec shellcheck {} +"
find .ci/scripts/ -type f -exec shellcheck {} +

#find scripts/ -type f | grep -v scripts/winresources | xargs shellcheck
