#!/bin/sh

set -e
set -x

shellcheck bin/doe
bin/doe completion | shellcheck -
find .ci/scripts/ -type f -exec shellcheck {} +
#find scripts/ -type f | grep -v scripts/winresources | xargs shellcheck

set +x
