#!/bin/sh

func=$1
shift

case "${func}" in
	info) # Show info about your AWS
		eval "${CALL_FUNCTION}"
		;;
	completion)
		echo "init help"
		;;
	help|*) # Print this help
		eval "${HELP}"
		;;
esac
