#!/bin/sh

func=$1
shift

case "${func}" in
	init) # Init gcloud
		eval "${CALL_FUNCTION}"
		;;
	completion)
		list_module_functions "${BASH_SOURCE[0]}"
		;;
	help|*) # Print this help
		show_help "${BASH_SOURCE[0]}"
		;;
esac
