#!/bin/sh

show_help()
{
    CMD="$(basename $0)"

    [ $0 = $1 ] || CMD+=" $(basename $1)"

    echo "Usage:\n\t$CMD <command>\n\nCommnads:"
    grep ") #[ ]" $1 | sed "s/) #/$(echo "\t")/g"
}

show_help $@