#!/bin/sh

func=$1
shift

case "${func}" in
	ubuntu) # Quick start ubuntu/xenial64
		eval "${CALL_FUNCTION}"
		;;
	vms) # Show all vagrant VMs info 
		eval "${CALL_FUNCTION}"
		;;
	clean) # Clean all vagrant metadata
		eval "${CALL_FUNCTION}"
		;;
	latest) # Check vagrant updates
		eval "${CALL_FUNCTION}"
		;;
	comp)
		echo "ubuntu vms clean latest help"
		;;
	help|*) # Print this help
		eval "${HELP}"
		;;
esac
