#!/bin/sh

func=$1
shift

case "${func}" in
	show) # Print all checks
		eval "${CALL_FUNCTION}"
		;;
	all) # Verify all known environments
		eval "${CALL_FUNCTION}"
		;;
	completion)
		echo "show all help"
		;;
	help|*) # Print this help
		eval "${HELP}"
		;;
esac
