#!/bin/sh

shellcheck bin/doe
#find lib/core/ -type f | grep -v ".data" | xargs shellcheck
find ci/scripts/ -type f -exec shellcheck {} +

#find scripts/ -type f | grep -v scripts/winresources | xargs shellcheck
