#!/bin/sh

shellcheck bin/doe
find lib/core/_self/* -type f -exec shellcheck {} +
find ci/scripts/ -type f -exec shellcheck {} +

#find scripts/ -type f | grep -v scripts/winresources | xargs shellcheck
