#!/bin/sh 

${mod}_${func}_opts=\"${opt}\"

${mod}_${func}()
{
    while getopts \$${mod}_${func}_opts o
    do
	case \$o in
	    '?')
		echo "invalid options"
		exit 1
		;;
	    \$o)
		eval arg_opt_\$o=\${OPTARG}
		;;
	esac
    done

    echo \"Your function with agruments\"
    declare -p | grep arg_opt_
}

${mod}_${func} "\"\$@\""