#!/bin/sh

echo "INSTALL $DOE"

set -e
set -x
DOE="/usr/local/bin/doe"
curl -fsSL https://doe.cloud/get | sudo sh
[ "$(command -v doe)" = "$DOE" ]
[ -e "$DOE" ]
[ "$(stat -c "%a" "$DOE")" = 755 ]
set +x
