#!/bin/sh

set -x
#set -e
DOE="/usr/local/bin/doe"

echo "INSTALL $DOE"
curl -fsSL https://doe.cloud/get | sudo sh
[ "$(command -v doe)" = "$DOE" ]
[ -e "$DOE" ]
[ "$(stat -c "%a" "$DOE")" = 755 ]

echo "CALL $DOE <some>"
[ "$(doe list-modules)" = "create completion " ]
[ -e "$(doe create -m mod -f func)" ]
doe mod func

set +x
