#!/bin/sh
# shellcheck disable=2086
#set -e

DOE="/usr/local/bin/doe"

echo "INSTALL $DOE"
curl -fsSL https://doe.cloud/get | sudo sh	; echo '$? curl -fsSL https://doe.cloud/get | sudo sh'
[ "$(command -v doe)" = "$DOE" ]		; echo '$? [ "$(command -v doe)" = "$DOE" ]'
[ -e "$DOE" ]					; echo '$? [ -e "$DOE" ]'
[ "$(stat -c "%a" "$DOE")" = 755 ]		; echo '$? [ "$(stat -c "%a" "$DOE")" = 755 ]'

echo "CALL $DOE <some>"
[ "$(doe list-modules)" = "create completion " ]; echo '$? [ "$(doe list-modules)" = "create completion " ]'
[ -e "$(doe create -m mod -f func)" ]		; echo '$? [ -e "$(doe create -m mod -f func)" ]'
[ $(doe mod func) ]				; echo '$? [ "$(doe mod func)" ]'
