#!/bin/sh

set -e

DOE="/usr/local/bin/doe"

curl -fsSL https://doe.cloud/get | sudo sh
echo "$0: curl -fsSL https://doe.cloud/get | sudo sh => $?"

[ "$(command -v doe)" = "$DOE" ]
echo "$0: [ \"\$(command -v doe)\" = \"$DOE\" ] => $?"

[ -e "$DOE" ]
echo "$0: [ -e \"$DOE\" ] => $?"

doe list-modules
