#!/bin/sh
# shellcheck disable=SC2039,SC1090

set -x
#set -e
DOE="/usr/local/bin/doe"

echo "INSTALL $DOE"
curl -fsSL https://doe.cloud/get | sudo sh
[ "$(command -v doe)" = "$DOE" ]
[ -e "$DOE" ]
[ "$(stat -c "%a" "$DOE")" = 755 ]

echo "INIT COMPLETION"
doe completion > completion.inc
source ./completion.inc
[ "$(typeset -F)" = "declare -f _doe_completion" ]

echo "CALL $DOE <some>"
[ "$(doe list-modules)" = "create completion " ]

doe completion

[ -e "$(doe create -m mod -f func)" ]
doe mod func

set +x
